services:
  db:
    image: mysql:8.0
    container_name: management-mysql-db
    environment:
      MYSQL_ROOT_PASSWORD: ${MYSQL_ROOT_PASSWORD}
      MYSQL_DATABASE: ${MYSQL_DATABASE}
      MYSQL_USER: ${MYSQL_USER}
      MYSQL_PASSWORD: ${MYSQL_PASSWORD}
    ports:
      - "3306:3306"
    healthcheck:
      test: [ "CMD", "mysqladmin", "ping", "-h", "localhost" ]
      interval: 10s
      timeout: 5s
      retries: 5
    volumes:
      - mysql_data:/var/lib/mysql

  frontend:
    build:
      context: ./music-teacher-management-frontend
      dockerfile: Dockerfile
    container_name: music-teacher-frontend
    ports:
      - "5173:5173"
    environment:
      VITE_API_URL: "http://localhost:8080"
    volumes:
      - ./music-teacher-management-frontend:/app
      - /app/node_modules

  backend:
    build:
      context: ./music-teacher-management
      dockerfile: Dockerfile
    container_name: music-teacher-backend
    ports:
      - "8080:8080"
    environment:
      SPRING_DATASOURCE_URL: "jdbc:mysql://db:3306/${MYSQL_DATABASE}"
      SPRING_DATASOURCE_USERNAME: ${MYSQL_USER}
      SPRING_DATASOURCE_PASSWORD: ${MYSQL_PASSWORD}
    depends_on:
      db:
        condition: service_healthy

volumes:
  mysql_data: